### ISSUE TITLE
Out of bound problem 

### ISSUE THREAD

**Issue by EunseongBoo** [zhen8838/K210_Yolo_framework#17]
Hello, I am having 'out of bound' problem when running "make train" & "make inference".

When I execute the command "make inference MODEL=yolo_mobilev1 DEPTHMUL=0.75 CKPT=asset/yolo_model.h5 IMG=data/people.jpg" in ubuntu,  the following error appears.

```
ubuntu@ubuntu:~/user/project/darkflow/K210_Yolo_framework$ make inference MODEL=yolo_mobilev1 DEPTHMUL=0.75 CKPT=asset/yolo_model.h5 IMG=data/people.jpg
python3 ./keras_inference.py \
                asset/yolo_model.h5 \
                data/people.jpg \
                --train_set voc \
                --class_num 20 \
                --model_def yolo_mobilev1 \
                --depth_multiplier 0.75 \
                --obj_thresh 0.7 \
                --iou_thresh 0.5 \
                --image_size 224 320 \
                --output_size 7 10 14 20
2020-07-01 16:55:37.626185: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2020-07-01 16:55:37.633894: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200000000 Hz
2020-07-01 16:55:37.636912: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x560326e935b0 executing computations on platform Host. Devices:
2020-07-01 16:55:37.636975: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2020-07-01 16:55:37.638829: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2020-07-01 16:55:38.277273: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:3b:00.0
2020-07-01 16:55:38.278141: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 1 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:5e:00.0
2020-07-01 16:55:38.278926: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 2 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:b1:00.0
2020-07-01 16:55:38.279710: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 3 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:d9:00.0
2020-07-01 16:55:38.280005: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.1
2020-07-01 16:55:38.281750: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10
2020-07-01 16:55:38.283322: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10
2020-07-01 16:55:38.283650: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10
2020-07-01 16:55:38.285382: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10
2020-07-01 16:55:38.286139: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10
2020-07-01 16:55:38.289717: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2020-07-01 16:55:38.295807: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0, 1, 2, 3
2020-07-01 16:55:38.295879: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.1
2020-07-01 16:55:38.299607: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-01 16:55:38.299625: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 1 2 3
2020-07-01 16:55:38.299630: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N N N N
2020-07-01 16:55:38.299634: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 1:   N N N N
2020-07-01 16:55:38.299638: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 2:   N N N N
2020-07-01 16:55:38.299641: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 3:   N N N N
2020-07-01 16:55:38.304238: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10312 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id:0000:3b:00.0, compute capability: 7.5)
2020-07-01 16:55:38.306208: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10312 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080 Ti, pci bus id:0000:5e:00.0, compute capability: 7.5)
2020-07-01 16:55:38.308043: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 10312 MB memory) -> physical GPU (device: 2, name: GeForce RTX 2080 Ti, pci bus id:0000:b1:00.0, compute capability: 7.5)
2020-07-01 16:55:38.309859: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 10312 MB memory) -> physical GPU (device: 3, name: GeForce RTX 2080 Ti, pci bus id:0000:d9:00.0, compute capability: 7.5)
2020-07-01 16:55:38.312105: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56032968bf20 executing computations on platform CUDA. Devices:
2020-07-01 16:55:38.312125: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-07-01 16:55:38.312134: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (1): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-07-01 16:55:38.312141: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (2): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-07-01 16:55:38.312147: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (3): GeForce RTX 2080 Ti, Compute Capability 7.5
Traceback (most recent call last):
  File "./keras_inference.py", line 201, in <module>
    args.test_image)
  File "./keras_inference.py", line 76, in main
    h = Helper(None, class_num, f'data/{train_set}_anchor.npy', np.reshape(np.array(image_size), (-1, 2)), np.reshape(np.array(output_size), (-1, 2)))
  File "/home/ubuntu/user/project/darkflow/K210_Yolo_framework/tools/utils.py", line 77, in __init__
    self.xy_offset = Helper._coordinate_offset(self.anchors, self.out_hw)  # type:np.ndarray
  File "/home/ubuntu/user/project/darkflow/K210_Yolo_framework/tools/utils.py", line 250, in _coordinate_offset
    grid_y = np.tile(np.reshape(np.arange(0, stop=out_hw[l][0]), [-1, 1, 1, 1]), [1, out_hw[l][1], 1, 1])
IndexError: index 2 is out of bounds for axis 0 with size 2
Makefile:66: recipe for target 'inference' failed
make: *** [inference] Error 1
```

I created the train.txt and voc_img_ann.npy by following the command below.
```
wget https://pjreddie.com/media/files/VOCtrainval_11-May-2012.tar
wget https://pjreddie.com/media/files/VOCtrainval_06-Nov-2007.tar
wget https://pjreddie.com/media/files/VOCtest_06-Nov-2007.tar
tar xf VOCtrainval_11-May-2012.tar
tar xf VOCtrainval_06-Nov-2007.tar
tar xf VOCtest_06-Nov-2007.tar
wget https://pjreddie.com/media/files/voc_label.py
python3 voc_label.py
cat 2007_train.txt 2007_val.txt 2012_*.txt > train.txt

python3 make_voc_list.py ../train.txt data/voc_img_ann.npy
```
How can I solve the problem? 

Thanks.

**Comment by zhen8838** [comment]
May be you should use :
`make anchors DATASET=voc ANCNUM=3 LOW='.0 .0' HIGH='1. 1.'`

because it needs specify `out_hw` and `anchor_num` etc:
```
	python3 ./make_anchor_list.py \
			${DATASET} \
			--max_iters 10 \
			--is_random True \
			--in_hw ${IMGSIZE} \
			--out_hw ${OUTSIZE} \
			--anchor_num ${ANCNUM} \
			--low ${LOW} \
			--high ${HIGH}
```
