### ISSUE TITLE
Train Error

### ISSUE THREAD

**Issue by Asterisci** [zhen8838/K210_Yolo_framework#35]
I succeed on Training on Voc and get the img.

And i download the model `yolo_mobilev1 0.75`, put it in `/data`

When i try `make train MODEL=yolo_mobilev1 DEPTHMUL=0.75 MAXEP=10 ILR=0.0001 DATASET=voc CLSNUM=20 IAA=True BATCH=16 CKPT=log/voc/yolo_model.h5`

it returns 

```
(k210_yolo_tf1) [chaoers@fanfan-Arch K210_Yolo_framework]$ make train MODEL=yolo_mobilev1      DEPTHMUL=0.75 MAXEP=10 ILR=0.0001 DATASET=voc CLSNUM=20 IAA=True BATCH=16 CKPT=log/voc/yolo_model.h5
python3 ./keras_train.py \
                --train_set voc \
                --class_num 20 \
                --pre_ckpt log/voc/yolo_model.h5 \
                --model_def yolo_mobilev1 \
                --depth_multiplier 0.75 \
                --augmenter True \
                --image_size 224 320 \
                --output_size 7 10 14 20 \
                --batch_size 16 \
                --rand_seed 3 \
                --max_nrof_epochs 10 \
                --init_learning_rate 0.0001 \
                --learning_rate_decay_factor 0 \
                --obj_weight 1 \
                --noobj_weight 1 \
                --wh_weight 1 \
                --obj_thresh 0.7 \
                --iou_thresh 0.5 \
                --vaildation_split 0.05 \
                --log_dir log \
                --is_prune False \
                --prune_initial_sparsity 0.5 \
                --prune_final_sparsity 0.9 \
                --prune_end_epoch 5 \
                --prune_frequency 100 
2021-03-05 08:53:25.698336: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-03-05 08:53:25.706801: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3400410000 Hz
2021-03-05 08:53:25.707261: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55740eac0640 executing computations on platform Host. Devices:
2021-03-05 08:53:25.707304: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2021-03-05 08:53:25.708469: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2021-03-05 08:53:25.929544: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-05 08:53:25.929817: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce GTX 1060 3GB major: 6 minor: 1 memoryClockRate(GHz): 1.7085
pciBusID: 0000:05:00.0
2021-03-05 08:53:25.929953: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory
2021-03-05 08:53:25.930057: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory
2021-03-05 08:53:25.930160: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory
2021-03-05 08:53:25.930253: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory
2021-03-05 08:53:25.930344: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory
2021-03-05 08:53:25.930433: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory
2021-03-05 08:53:25.930533: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory
2021-03-05 08:53:25.930558: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...
2021-03-05 08:53:26.001765: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-03-05 08:53:26.001828: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2021-03-05 08:53:26.001837: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2021-03-05 08:53:26.003390: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-05 08:53:26.003801: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55740f50c890 executing computations on platform CUDA. Devices:
2021-03-05 08:53:26.003840: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce GTX 1060 3GB, Compute Capability 6.1
[ INFO  ] data augment is  True
WARNING:tensorflow:From /home/chaoers/anaconda3/envs/k210_yolo_tf1/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py:494: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.
    
WARNING:tensorflow:From /home/chaoers/anaconda3/envs/k210_yolo_tf1/lib/python3.7/site-packages/tensorflow/python/data/util/random_seed.py:58: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
2021-03-05 08:53:26.197747: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-03-05 08:53:26.198099: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce GTX 1060 3GB major: 6 minor: 1 memoryClockRate(GHz): 1.7085
pciBusID: 0000:05:00.0
2021-03-05 08:53:26.198326: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory
2021-03-05 08:53:26.198567: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory
2021-03-05 08:53:26.198740: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory
2021-03-05 08:53:26.198915: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory
2021-03-05 08:53:26.199223: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory
2021-03-05 08:53:26.199594: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory
2021-03-05 08:53:26.199729: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory
2021-03-05 08:53:26.199764: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...
2021-03-05 08:53:26.200140: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-03-05 08:53:26.200185: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      
WARNING:tensorflow:Entity <function Helper._create_dataset.<locals>._parser_wrapper at 0x7f1def3c0c80> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function Helper._create_dataset.<locals>._parser_wrapper at 0x7f1def3c0c80>: AssertionError: Bad argument number for Name: 3, expecting 4
[ INFO  ] data augment is  False
WARNING:tensorflow:Entity <function Helper._create_dataset.<locals>._parser_wrapper at 0x7f1def3c0d90> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function Helper._create_dataset.<locals>._parser_wrapper at 0x7f1def3c0d90>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:From /home/chaoers/anaconda3/envs/k210_yolo_tf1/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Traceback (most recent call last):
  File "./keras_train.py", line 154, in <module>
    args.prune_frequency)
  File "./keras_train.py", line 50, in main
    yolo_model, yolo_model_warpper = network([image_size[0], image_size[1], 3], len(h.anchors[0]), class_num, alpha=depth_multiplier)
  File "/home/chaoers/workspace/K210_Yolo_framework/models/yolonet.py", line 19, in yolo_mobilev1
    base_model.load_weights('data/mobilenet_v1_base_7.h5')
  File "/home/chaoers/anaconda3/envs/k210_yolo_tf1/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 162, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/home/chaoers/anaconda3/envs/k210_yolo_tf1/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 1424, in load_weights
    saving.load_weights_from_hdf5_group(f, self.layers)
  File "/home/chaoers/anaconda3/envs/k210_yolo_tf1/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 711, in load_weights_from_hdf5_group
    original_keras_version = f.attrs['keras_version'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'
make: *** [Makefile:35: train] Error 1
```

**Comment by zhen8838** [comment]
加载模型的内部错误吧，可能是我导出的软件包版本与你目前使用的版本不同。可以参考下这个[链接](https://stackoverflow.com/questions/53740577/does-any-one-got-attributeerror-str-object-has-no-attribute-decode-whi)。

**Comment by Asterisci** [comment]
我是使用conda新增了一个`3.7.1`的python环境，然后安装`requirement.txt`的包，请问可能是那里的环境有问题呢
`arch`和`mac`系统测试都出现这个问题

**Comment by zhen8838** [comment]
stackoverflow这个人提到只修改tf或者keras的版本不能解决问题，将h5py降级到2.10.0才能解决问题，你可以尝试一下。
```
For me the solution was downgrading the h5py package (in my case to 2.10.0), apparently putting back only Keras and Tensorflow to the correct versions was not enough.
```

**Comment by Asterisci** [comment]
使用`pip install 'h5py==2.10.0' --force-reinstall`后重新运行，新报错

```
AttributeError: module 'gast' has no attribute 'Index'
```

但是好像可以训练，等会去arch上试一下

但是我应该是用conda创建了和demo一样的环境了为啥会有版本问题呢，不是很明白

**Comment by zhen8838** [comment]
可能是由于conda或者pip安装的包依赖有时候由于一些潜在的安全问题被升级到了较新的版本，但新版本与旧代码存在了冲突。

**Comment by BackMountainDevil** [comment]
?把error的错误提示写在标题里面这样一眼就知道啥错误的。此问题已有解决方案

**Comment by Asterisci** [comment]
thx
