### ISSUE TITLE
训练自己的数据集报错：ValueError: operands could not be broadcast together with shapes (0,0) (2,)

### ISSUE THREAD

**Issue by xiaoxiaolu1111** [zhen8838/K210_Yolo_framework#52]
python3 ./make_anchor_list.py \
                voc \
                --max_iters 10 \
                --is_random True \
                --in_hw 224 320 \
                --out_hw 7 10 14 20 \
                --anchor_num 3 \
                --low 0.0 0.0 \
                --high 1.0 1.0
Traceback (most recent call last):
  File "./make_anchor_list.py", line 241, in <module>
    main(args.train_set, args.max_iters, args.in_hw, args.out_hw, args.anchor_num, args.is_random, args.is_plot, args.low, args.high)
  File "./make_anchor_list.py", line 198, in main
    X[i, 1][:, 1:3] = (X[i, 1][:, 1:3] * img_wh * scale + translation) / in_wh
ValueError: operands could not be broadcast together with shapes (0,0) (2,) 
Makefile:79: recipe for target 'anchors' failed
make: *** [anchors] Error 1

**Comment by zhen8838** [comment]
你这个应该是数据集的标注有出错的.
